package com.example.MBG2.entity;

public class Class {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.id
     *
     * @mbg.generated Fri Nov 27 13:50:03 CST 2020
     */
    private Byte id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.name
     *
     * @mbg.generated Fri Nov 27 13:50:03 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.student_id
     *
     * @mbg.generated Fri Nov 27 13:50:03 CST 2020
     */
    private Integer studentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.id
     *
     * @return the value of class.id
     *
     * @mbg.generated Fri Nov 27 13:50:03 CST 2020
     */
    public Byte getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.id
     *
     * @param id the value for class.id
     *
     * @mbg.generated Fri Nov 27 13:50:03 CST 2020
     */
    public void setId(Byte id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.name
     *
     * @return the value of class.name
     *
     * @mbg.generated Fri Nov 27 13:50:03 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.name
     *
     * @param name the value for class.name
     *
     * @mbg.generated Fri Nov 27 13:50:03 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.student_id
     *
     * @return the value of class.student_id
     *
     * @mbg.generated Fri Nov 27 13:50:03 CST 2020
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.student_id
     *
     * @param studentId the value for class.student_id
     *
     * @mbg.generated Fri Nov 27 13:50:03 CST 2020
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }
}