package com.example.MBG2.entity;

public class Course {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.id
     *
     * @mbg.generated Fri Nov 27 13:50:03 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.student_id
     *
     * @mbg.generated Fri Nov 27 13:50:03 CST 2020
     */
    private Integer studentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.subject_id
     *
     * @mbg.generated Fri Nov 27 13:50:03 CST 2020
     */
    private String subjectId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.id
     *
     * @return the value of course.id
     *
     * @mbg.generated Fri Nov 27 13:50:03 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.id
     *
     * @param id the value for course.id
     *
     * @mbg.generated Fri Nov 27 13:50:03 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.student_id
     *
     * @return the value of course.student_id
     *
     * @mbg.generated Fri Nov 27 13:50:03 CST 2020
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.student_id
     *
     * @param studentId the value for course.student_id
     *
     * @mbg.generated Fri Nov 27 13:50:03 CST 2020
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.subject_id
     *
     * @return the value of course.subject_id
     *
     * @mbg.generated Fri Nov 27 13:50:03 CST 2020
     */
    public String getSubjectId() {
        return subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.subject_id
     *
     * @param subjectId the value for course.subject_id
     *
     * @mbg.generated Fri Nov 27 13:50:03 CST 2020
     */
    public void setSubjectId(String subjectId) {
        this.subjectId = subjectId == null ? null : subjectId.trim();
    }
}