package com.example.MBG2.mapper;

import com.example.MBG2.entity.Class;

public interface ClassMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbg.generated Fri Nov 27 13:50:03 CST 2020
     */
    int insert(Class record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbg.generated Fri Nov 27 13:50:03 CST 2020
     */
    int insertSelective(Class record);
}